config/routes.rb
SampleApp::Application.routes.draw do

=begin
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
=end
resources :users do 
  member do
    get :following, :followers
  end
end

resources :authentications 
resources :sessions, only: [:new, :create, :destroy]
resources :microposts, only: [:create, :destroy]
resources :relationships, only: [:create, :destroy]

root 'static_pages#home'
match '/help', to: 'static_pages#help', via: 'get'
match '/about', to: 'static_pages#about', via: 'get'
match '/contact', to: 'static_pages#contact', via: 'get'
get '/auth/:provider/callback' => 'authentications#create'

match '/signup', to: 'users#new', via: 'get'
match '/signin', to: 'sessions#new', via: 'get'
match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
	belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
  	#if the current_user exist get the authentication options
  	@authentications = current_user.authentications if current_user
  end

  def create
  	omniauth = request.env['omniauth.auth']
  	authentication = Authentication.find_by_provider_and_uid(omniauth['provider'],
  	                                                               omniauth['uid'])
  	if authentication
  		user = authentication.user
  		sign_in(user)
  		flash[:notice] = "Signed in successfully"
  		redirect_to user
  	elsif current_user
		current_user.authentications.create!(:provider => omniauth['provider'], 
			                                         :uid => omniauth['uid'] )
		flash[:notice] = "Authentication successfully"
		redirect_to authentications_path
	else
		@user = User.new
		@user.apply_omniauth(omniauth)
		if @user.save
			sign_in(@user)
	  		flash[:notice] = "Signed in successfully"
	  		redirect_to @user
	  	else
	  		session[:omniauth] = omniauth.except('extra')
	  		redirect_to new_user_path
	  	end
  	end
  end

  def destroy
  	@authentication = current_user.authentications.find(params[:id])
  	@authentication.destroy
  	flash[:notice] = "successfully destroyed authentication."
  	redirect_to authentications_path
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
	
end

app/views/authentications/index.html.haml
= provide(:title, "Authentication")
-if @authentications
 -unless @authentications.empty?
  %p
   %strong You can sign in to this account using:
  .authentications
   -for authentication in @authentications
    .authentication
     = image_tag "#{authentication.provider}_32.png", :size => "32x32"
     .provider=authentication.provider.titleize
     .uid=authentication.uid
     = link_to "X", authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => 'delete', :class => 'remove'
   .clear
  %br
  %br
  %p
   %strong.add_service Add another service to sign in with: 
-else
 %p
  %strong Sign in through one ot these services:

%a{href: "/auth/twitter" , class: "auth_provider"}
 = image_tag "twitter_64.png", :size => "64x64", :alt => "Twitter" 
 Twitter
%a{href: "/auth/facebook" , class: "auth_provider"}
 = image_tag "facebook_64.png", :size => "64x64", :alt => "Facebook" 
 Facebook
%a{href: "/auth/google_app" , class: "auth_provider"}
 = image_tag "google_64.png", :size => "64x64", :alt => "Google" 
 Google
%a{href: "/auth/open_id" , class: "auth_provider"}
 = image_tag "openid_64.png", :size => "64x64", :alt => "OpenID" 
 OpenID
.statment_signin_signup
 %span Don't use these services?
 = link_to "Sign up", new_user_path
 %span Or
 = link_to "Sign in", new_session_path
 %span with password
 .clear
-#= debug(session) if Rails.env.development?