config/routes.rb
SampleApp::Application.routes.draw do

=begin
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
=end
resources :users do 
  member do
    get :following, :followers
  end
end

resources :authentications 
resources :sessions, only: [:new, :create, :destroy]
resources :microposts, only: [:create, :destroy]
resources :relationships, only: [:create, :destroy]

root 'static_pages#home'
match '/help', to: 'static_pages#help', via: 'get'
match '/about', to: 'static_pages#about', via: 'get'
match '/contact', to: 'static_pages#contact', via: 'get'
get '/auth/:provider/callback' => 'authentications#create'

match '/signup', to: 'users#new', via: 'get'
match '/signin', to: 'sessions#new', via: 'get'
match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.haml
- if params[:action] == 'index' && params[:controller] == 'authentications'
 %footer{ class: "auth_footer" }
  %small
   %a{href: "http://railstutorial.org/"} Rails Tutorial 
   by Michael Hartl
  %nav
   %ul
    %li= link_to "About", about_path
    %li= link_to "Contact", contact_path
    %li 
     %a{href: href="http://news.railstutorial.org/"} News
-else
 %footer{ class: "footer" }
  %small
   %a{href: "http://railstutorial.org/"} Rails Tutorial 
   by Michael Hartl
  %nav
   %ul
    %li= link_to "About", about_path
    %li= link_to "Contact", contact_path
    %li 
     %a{href: href="http://news.railstutorial.org/"} News



 

app/views/layouts/_header.html.haml
%header{ class: "navbar navbar-fixed-top navbar-inverse" }
 %div{class: 'navbar-inner'}
  %div{class: "container"}
   = link_to "sample app", root_path, id: "logo" 
   %nav
    %ul{ class: "nav pull-right" }
     %li= link_to "Home", root_path 
     %li= link_to "Help", help_path
     - if signed_in? 
      %li= link_to "Users", users_path
      %li{id: "fat-menu", class: "dropdown" }
       %a.dropdown-toggle{ :href =>  "#" , "data-toggle" => "dropdown"} 
        Account 
        %b{ class: "caret" }
       %ul.dropdown-menu
        %li= link_to "Profile", current_user
        %li= link_to "Settings", edit_user_path(current_user)
        %li{ class: "divider"}
        %li
         = link_to "Sign out", signout_path, method: "delete"
     - else
      %li= link_to "Sign in", signin_path
      %li.bar= "|"
      %li= link_to "Other options", authentications_path

app/views/layouts/_shim.html.haml
<!--[if lt IE 9]<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

app/views/layouts/application.html.haml
!!!5
-#haml comment 
%html
 %head
 %title= full_title(yield(:title))
 = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
 = javascript_include_tag "application", "data-turbolinks-track" => true 
 = csrf_meta_tags
 = render 'layouts/shim'
 %body
  = render 'layouts/header'
  %div{class: "container"}
   - flash.each do | key, value |
    %div{class: "alert alert-#{key}"}= value
   = yield
   = render 'layouts/footer'
   = debug(params) if Rails.env.development?
  
  